# -*- coding: utf-8 -*-
"""taller8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ipSKWYrv0_DC9pZR1JCv_GbvaeBXiCS
"""

import math

def calcular_seno_radianes(x, epsilon):
    valor_estimado = 0.0
    iteraciones = 0
    n = 0

    while True:
        termino = ((-1) ** n) * (x ** (2 * n + 1)) / math.factorial(2 * n + 1)
        valor_estimado += termino

        iteraciones += 1

        if abs(termino) < epsilon:
            break

        n += 1

    error_aproximado = abs(termino / valor_estimado) * 100

    return valor_estimado, error_aproximado, iteraciones

def main():
    x = float(input("Ingrese el valor en radianes: "))
    epsilon = float(input("Ingrese el criterio de error esperado (εs): "))

    valor_estimado, error_aproximado, iteraciones = calcular_seno_radianes(x, epsilon)

    print(f"El valor estimado del seno de {x} es: {valor_estimado}")
    print(f"El error aproximado relativo porcentual es: {error_aproximado:.8f}%")
    print(f"Número de iteraciones realizadas: {iteraciones}")

if __name__ == "__main__":
    main()