# -*- coding: utf-8 -*-
"""taller 21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyM3eyrSMaQL6eFxGOtzK8zsAvW9RYDl
"""

import numpy as np

x = np.array([1, 3, 5, 7, 9, 11, 13])
y = np.array([7.4, 1.8, -1, -1.8, -1.2, 2.2, 7.2])

coefficients = np.polyfit(x, y, 2)

a, b, c = coefficients

polynomial = np.poly1d(coefficients)

y_pred = polynomial(x)

correlation_matrix = np.corrcoef(x, y)
correlation_coefficient = correlation_matrix[0, 1]

print("Coeficientes del polinomio de segundo grado:")
print("a =", a)
print("b =", b)
print("c =", c)
print("\nPolinomio ajustado:")
print(polynomial)
print("\nCoeficiente de correlación (r):", correlation_coefficient)