# -*- coding: utf-8 -*-
"""taller 19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9qYn51LlbpihUwcoExCLrmMnASTrHPv
"""

import numpy as np
import matplotlib.pyplot as plt

# Datos
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array([4.3, 6.5, 7.5, 8, 8.5, 8.8, 9, 9.5])

# Regresión para la ecuación de potencias
a_potencia, b_potencia = np.polyfit(np.log(x), np.log(y), 1)
y_potencia = np.exp(a_potencia) * x ** b_potencia

# Regresión para la razón de crecimiento
a_crecimiento, b_crecimiento = np.polyfit(x, y, 1)
y_crecimiento = a_crecimiento * x + b_crecimiento

# Plotting
plt.scatter(x, y, label='Datos')
plt.plot(x, y_potencia, label=f'Ecuación de potencias: {np.exp(a_potencia):.2f} * x^{b_potencia:.2f}', color='red')
plt.plot(x, y_crecimiento, label=f'Razón de crecimiento: {a_crecimiento:.2f} * x + {b_crecimiento:.2f}', color='green')

plt.title('Regresiones Lineales por Mínimos Cuadrados')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()