# -*- coding: utf-8 -*-
"""taller 18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wb2nKQ0hMwCS6_-tyWLj5yEmDW0-Kqzq
"""

import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

x_data = np.array([1, 2, 3, 4, 5, 6])
y_data = np.array([1.6, 2.3, 3.4, 4.5, 6.4, 9])

def exponential_func(x, a, b):
    return a * np.exp(b * x)

params, covariance = curve_fit(exponential_func, x_data, y_data)

a, b = params

x_fit = np.linspace(min(x_data), max(x_data), 100)
y_fit = exponential_func(x_fit, a, b)

plt.scatter(x_data, y_data, label='Datos')
plt.plot(x_fit, y_fit, color='red', label='Curva Ajustada')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regresión Exponencial')
plt.legend()
plt.grid(True)
plt.show()

print("Parámetros de la regresión exponencial:")
print("a =", a)
print("b =", b)