# -*- coding: utf-8 -*-
"""taller 22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PW95gsV1tI5bGcBiIShzzCm8eV5wpl7Y
"""

import numpy as np
from scipy.stats import linregress

data = np.array([
    [1, 0, 0.6],
    [1, 1, 2],
    [2, 1, 0.1],
    [3, 2, 0.3],
    [1, 2, 2.2],
    [2, 3, 2.3],
    [3, 3, 0.8],
    [3, 1, -1]
])

x1 = data[:, 0]
x2 = data[:, 1]
y = data[:, 2]

X = np.column_stack((x1, x2, np.ones_like(x1)))

coefficients, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

m1, m2, c = coefficients

r = np.corrcoef(np.dot(X, coefficients), y)[0, 1]

print("Coeficientes del modelo lineal:")
print("m1:", m1)
print("m2:", m2)
print("c:", c)
print("Coeficiente de correlación (r):", r)