# -*- coding: utf-8 -*-
"""taller 24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMO4IN1N4dhLa_yPvjPzJztunN-_gFaK
"""

def lagrange_interpolation(points):
    def L(i, x, points):
        result = 1
        for j, point in enumerate(points):
            if i != j:
                result *= (x - point[0]) / (points[i][0] - point[0])
        return result

    def P(x, points):
        result = 0
        for i, point in enumerate(points):
            result += point[1] * L(i, x, points)
        return result

    return P

points = [(1, 2), (2, 1.8), (3, -2), (4, -4.6), (5, 3.6)]

interpolating_polynomial = lagrange_interpolation(points)

print("Polinomio de interpolación de Lagrange:")
print(interpolating_polynomial.__doc__)