# -*- coding: utf-8 -*-
"""taller1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJ9GQpf8G60md1dL91-nIB2xME9C291N
"""

cantidad_a = int(input("numero de elementos del conjunto A:"))

a=set()
for i in range(cantidad_a):
  elemento = int(input("elemento"+ str(i+1)+": "))
  a.add(elemento)
  print(a)

cantidad_a = int(input("numero de elementos del conjunto A "))
cantidad_b = int(input("numero de elementos del conjunto B "))
a=set()
for i in range(cantidad_a):
  elemento = float(input("elemento"+ str(i+1)+": "))
  a.add(elemento)
print(a)

b=set()
for i in range(cantidad_b):
  elemento = float(input("elemento"+ str(i+1)+": "))
  b.add(elemento)
print(b)

print("¿Que operacion quiere realizar?\n 1)union\n 2)interseccion\n 3)diferencia\n 4)diferencia cimetrica")
op=int(input())
if op==1:
  R=a|b
  print(R)
if op==2:
  R=a&b
  print(R)
if op==3:
  print("1)diferencia de a-b\n 2)diferencia de b-a")
  otrop=int(input())
  if otrop==1:
    RT=a-b
    print(R)
  if otrop==2:
    RT=b-a
    print(R)
if op==4:
  R=a^b
  print(R)
print("cardinalidad",6len(R))