# -*- coding: utf-8 -*-
"""punto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igwELU4SpT3B3EyW4zX6e4M0Co6TjTpO
"""

import numpy as np

A = np.array([[3, 1, 0],
              [4, -1, 1],
              [8, 3, -2]])

A_inv = np.linalg.inv(A)

print("Matriz inversa de A:")
print(A_inv)